### ISSUE TITLE
Investigate alternative authorization options

### ISSUE THREAD

**Issue by mcrider** [mcrider/dcap-node#4]
Ideally auth would be completely decentralized, or at least give users options to use different auth services, but my initial investigation hasn't lead to any great solutions. 

Blockstack is definitely worth looking into more but so far it seems the integration would be pretty clunky (e.g. requiring a blockstack app to be open). 

Though not decentralized, Keybase is allegedly working on an auth platform which we could also use with their encryption API. Keybase is a pretty great project so at least some sort of optional integration with dcap could be useful.

**Comment by vinniejames** [comment]
The Blockstack app will soon be available as a web interface, precluding the need to run the Blockstack app. The integration is super easy, I just used it for http://CoinKitty.co

**Comment by mcrider** [comment]
I've implemented IPFS as a storage solution and made it the default.  I'll keep my eye out for potential integrations with Blockstack and others, but closing this for now.
